# Generated by Django 5.2.8 on 2025-11-11 15:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chantiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_chantier', models.CharField(blank=True, max_length=180, unique=True)),
                ('contact', models.TextField(blank=True, default='Si besoin pendant le chantier...')),
                ('date_rdv_technique', models.DateField(blank=True, null=True)),
                ('travaux_type', models.JSONField(blank=True, default=list)),
                ('client_final_type', models.CharField(choices=[('Professionnel', 'Professionnel'), ('Particulier', 'Particulier')], default='Particulier', max_length=20)),
                ('adresse_chantier', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('cp_ville_chantier', models.CharField(max_length=16)),
                ('avancement_statut', models.JSONField(blank=True, default=list)),
                ('cr_next_step', models.JSONField(blank=True, default=list)),
                ('avancement_chantier', models.PositiveSmallIntegerField(default=0, help_text="Pourcentage d'avancement (0-100)", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('nbr_heures', models.PositiveIntegerField(default=0)),
                ('date_debut_chantier', models.DateField(blank=True, null=True)),
                ('date_fin_prevue_chantier', models.DateField(blank=True, null=True)),
                ('annee_periode_construction', models.CharField(blank=True, max_length=32)),
                ('gdrive_urls', models.JSONField(blank=True, default=list)),
                ('brief_url', models.URLField(blank=True)),
                ('devis_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nombre_de_jours_chantier', models.PositiveIntegerField(default=0)),
                ('telephone_contact', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')])),
                ('cout_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef_chantier', models.ForeignKey(blank=True, help_text="Chef de chantier must have user_type == 'Chef d'équipe'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chantiers_chef', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chantier',
                'verbose_name_plural': 'Chantiers',
                'db_table': 'chantiers',
                'ordering': ['-created_at'],
            },
        ),
    ]
