# Generated by Django 4.2.26 on 2025-11-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chantiers',
            name='ville_chantier',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
