# Generated by Django migration
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_chantiers_ville_chantier'),
    ]

    operations = [
        migrations.AddField(
            model_name='chantiers',
            name='number_hour_planned',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text='Heures planifiées calculées à partir du devis HT',
                max_digits=10
            ),
        ),
        migrations.AddField(
            model_name='chantiers',
            name='number_hour_spent_on_project',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text='Heures totales passées sur le chantier (somme des plannings)',
                max_digits=10
            ),
        ),
        migrations.AddField(
            model_name='chantiers',
            name='cost_spent_on_project',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text='Coût total dépensé sur le chantier (somme des cout_planning)',
                max_digits=12
            ),
        ),
    ]

