# Generated by Django 4.2.26 on 2025-11-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_chantiers_hours_and_cost_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='chantiers',
            name='va',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valeur ajoutée = Devis HT - Coût réel', max_digits=12),
        ),
    ]
