# Generated by Django 5.2.8 on 2025-11-11 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('numero_telephone', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')])),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('Secrétaire', 'Secrétaire'), ("Chef d'équipe", "Chef d'équipe"), ('Employé', 'Employé')], default='Employé', max_length=20)),
                ('cout_h', models.DecimalField(blank=True, decimal_places=2, help_text='Coût horaire en euros', max_digits=8, null=True)),
                ('cout_j', models.DecimalField(blank=True, decimal_places=2, help_text='Coût journalier en euros', max_digits=8, null=True)),
                ('competences', models.JSONField(blank=True, default=list)),
                ('permis_de_conduire', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
    ]
