# Generated by Django 5.2.8 on 2025-11-11 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('cout_planning', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='projects.chantiers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planning',
                'verbose_name_plural': 'Plannings',
                'db_table': 'planning',
                'ordering': ['date', 'start_hour'],
                'indexes': [models.Index(fields=['user', 'date'], name='planning_user_id_3580cb_idx'), models.Index(fields=['chantier', 'date'], name='planning_chantie_5cdfe1_idx')],
                'unique_together': {('user', 'date', 'start_hour', 'end_hour')},
            },
        ),
    ]
