# Generated by Django 5.2.8 on 2025-11-11 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pistes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=180)),
                ('statut', models.CharField(choices=[('Nouveau', 'Nouveau'), ('Qualifié', 'Qualifié'), ('Devis', 'Devis'), ('Gagné', 'Gagné'), ('Perdu', 'Perdu')], default='Nouveau', max_length=20)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('montant_estime', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('probabilite', models.PositiveSmallIntegerField(default=0, help_text='Probabilité de conversion (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date_relance', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Piste',
                'verbose_name_plural': 'Pistes',
                'db_table': 'pistes',
                'ordering': ['-created_at'],
            },
        ),
    ]
